### ISSUE TITLE
Error occurred at: src/browsers.c - parse_browsers_file - 382

### ISSUE THREAD

**Issue by jasonatcisco** [hectorm/docker-goaccess#1]
Hey there hectorm!

Thank you for making a build for ARM and nginx. I am having a bit of an issue deploying on my raspi swarm.

Receiving this error when deploying the config. My Nginx container starts fine so I am confident in my NFS mounting and other config.

Thoughts?

```
GoAccess - version 1.5.5 - Feb 14 2022 03:44:37
Config file: /etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/browsers.c - parse_browsers_file - 382
Unable to open browser's file: No such file or directory
```

version: '3.2'

services:
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "192.168.1.XXX"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "XXXX"
      DB_MYSQL_PASSWORD: "XXXX"
      DB_MYSQL_NAME: "XXXX"
    volumes:
      - nginx_data:/data
      - nginx_cert:/etc/letsencrypt
    networks:
      - nginx_network
    deploy:
      mode: replicated
      replicas: 1
  
  goaccess:
    image: hectormolinero/goaccess:latest        
    ports:
        - '7889:7889'
    volumes:
       - nginx_log:/opt/log
       - goaccess_data:/var/www/goaccess/
       - goaccess_config:/etc/goaccess/
    networks:
      - nginx_network
    deploy:
      mode: replicated
      replicas: 1

networks:
  nginx_network:
    driver: overlay
    attachable: true

volumes:
  nginx_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.XXX,nolock,soft,rw
      device: ":/volume1/docker/nginx/data"
  nginx_cert:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.XXX,nolock,soft,rw
      device: ":/volume1/docker/nginx/cert"
  nginx_log:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.XXX,nolock,soft,ro
      device: ":/volume1/docker/nginx/data/logs"
  goaccess_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.XXX,nolock,soft,rw
      device: ":/volume1/docker/goaccess/data"
  goaccess_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.XXX,nolock,soft,ro
      device: ":/volume1/docker/goaccess/config"

**Comment by hectorm** [comment]
I think the reason is that GoAccess cannot read the `/etc/goaccess/browsers.list` file, maybe because it is getting lost when mounting the `/etc/goaccess/` directory on a volume?

Please check if that file exists and can be read by GoAccess.
